a=1;
b=2;
suma=a+b;
print("la suma de ",a,"y",b,"es ",suma);
a=1;
b=2;
resta=a-b;
print("la resta de ",a,"y",b,"es ",resta);
a=1;
b=2;
multiplicacion=a*b;
print("la multipliccion de ",a,"y",b,"es ",multiplicacion);
a=1;
b=2;
division=a/b;
print("la division de ",a,"y",b,"es ",division);
a=1;
b=2;
potencia=a**b;
print("la potencia de ",a,"y",b,"es ",potencia);